spring:
  application:
    name: cinecollector
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cinecollector}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    property-naming-strategy: SNAKE_CASE

  jdbc:
    template:
      fetch-size: 100

  sql:
    init:
      mode: always
      continue-on-error: true

aws:
  s3:
    bucket: ${BUCKET_NAME}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  region: ${BUCKET_REGION}


logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: ${JWT_ACCESS_EXPIRE:3600000}     # 1시간
  refresh-token-expire-time: ${JWT_REFRESH_EXPIRE:1209600000} # 2주
